- name: conditions
  hosts: localhost
  tasks:
  - name: check robouser is exist or not
    ansible.builtin.command: id roboshop
    register: user 
    #ignore_erros: true 

  - name: print variable value
    ansible.builtin.debug:
      msg: "user is:{{user}}"